[build]
  publish = "."

[[redirects]]
  from = "/stats/script.js"
  to = "https://cloud.umami.is/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/stats/api/send"
  to = "https://cloud.umami.is/api/send"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
